plugins {
    id 'java'
    id "com.gradleup.shadow" version "9.3.1"
}

group 'org.mikeshafter'
version '1.21.101'

compileJava.options.encoding 'UTF-8'

repositories {
    mavenCentral()
    mavenLocal()
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
    maven {url 'https://oss.sonatype.org/content/groups/public/'}
    maven {url 'https://ci.mg-dev.eu/plugin/repository/everything'}
}

//java {
//    toolchain {
//        languageVersion = JavaLanguageVersion.of(21)
//    }
//}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.10-R0.1-SNAPSHOT'
    compileOnly 'com.bergerkiller.bukkit:BKCommonLib:1.21.10-v1-SNAPSHOT'
    compileOnly 'com.bergerkiller.bukkit:TrainCarts:1.21.10-v1-SNAPSHOT'
    compileOnly 'com.bergerkiller.bukkit:SignLink:1.20.4-v1-SNAPSHOT'

    compileOnly "org.incendo:cloud-paper"
    compileOnly "org.incendo:cloud-annotations"
    compileOnly "org.incendo:cloud-minecraft-extras"
}

shadowJar {
    minimize {}
    relocate "org.incendo.cloud", "com.bergerkiller.bukkit.common.dep.cloud"
}

assemble {
    dependsOn shadowJar
}

test {
    useJUnitPlatform()
}
