name: OldThrottle
version: ${project.version}
main: mikeshafter.oldthrottle.OldThrottle
api-version: 1.16
authors: [ MikeShafter ]
depend: [BKCommonLib]
commands:
  throttle:
    usage: /throttle <on|off>
    description: Toggles throttle
description: Old throttle system inspired by the JR 103 series.
